name: Scheduled Create Pull Request

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  GIT_AUTHOR_NAME: aryehky
  GIT_AUTHOR_EMAIL: kyky0112@gmail.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.email "$GIT_AUTHOR_EMAIL"
        git config --global user.name "$GIT_AUTHOR_NAME"

    - name: Randomly decide to make changes
      run: |
        rand=$(shuf -i 1-2 -n 1)
        if [ $rand -eq 1 ]; then
          echo "." >> README.md
        else
          echo "No changes made."
        fi

    - name: Check if changes were made
      run: |
        if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m "Update README.md"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GH_PAT }}
        commit-message: "Automated commit message"
        committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        author: "aryehky <kyky0112@gmail.com>"
        title: "Created pull request for Ui branch"
        body: |
          This pull request introduces a new features and components is designed to be customizable and reusable, providing consistent sections across the application.

        branch: ui # This is the branch the PR will be created from
        base: main # This is the target branch for the PR
        draft: false # Create a draft pull request (optional, set to true if you want it as draft)
